language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - npm test
  - npm run test:coverage
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
